# Generated by Django 5.0.6 on 2024-05-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorequest',
            name='video_file',
            field=models.BinaryField(),
        ),
    ]
