# Generated by Django 5.0.6 on 2024-05-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_videorequest_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videorequest',
            name='video_file',
        ),
    ]
